import javax.swing.JOptionPane;
import java.util.Scanner;
import java.io.*;
/**
 * This is a program that helps the users to calculate their grades based on a file(file can have mutiple lines with grades and use "-1" as a terminal) the user created.
 * The user need to enter the file's name that contains grades and give a name for the output file, whitch will
 * be generated by the computer.
 *
 * @author Qianyi Li
 * @version v1.0
 * @since 3/11/2025
 */
public class Grades{
    public static void main (String[] args) throws IOException{
        String inFile, outFile;

        inFile = getInFile();
        outFile = getOutFile();
        processFile(inFile, outFile);

        System.exit(0);
    }

    /**
     * This method can get the file with grades in it, and will also test whether the file exists or not.
     * @return the name/path of the file will return if it exist or will return "The file does not exist." if it dosn't.
     */
    public static String getInFile() throws IOException{
        String temp;

        temp = JOptionPane.showInputDialog("Enter the name of the input file(ie: input.txt)");
        File test = new File(temp);
        while(!test.exists()){
            temp = JOptionPane.showInputDialog("Enter the name of the input file(ie: input.txt)");
            test = new File(temp);
        }

        return temp;
    }

    /**
     *This method allows the user to create the name for the output file.
     *@return It will return the name of the outputfile based on the user's input.
     */
    private static String getOutFile() throws IOException{
        String temp;

        temp = JOptionPane.showInputDialog("Enter the name of the output file(ie: output.txt)");

        return temp;
    }

    /**
     * This method will calculate the user's grades including the number of grades(A-F), highest, lowest score and average.
     * @param inFile It is the input file's name/path with user's grades.
     * @param outFile It is the output file's name/path created by the user. 
     */
    public static void processFile(String inFile, String inOutFile)throws IOException{
        int number;//each number we detect.
        int A, B, C, D, F, min, max;//accumulators for each grades(A-F),highest and lowest grades
        int total, count;// total grades and the number of exams
        int set = 1;//the number of sets calculated
        double avg;
        File inFileName = new File(inFile);
        Scanner input = new Scanner(inFileName);
        PrintWriter output = new PrintWriter(inOutFile);
        
        while(input.hasNextLine()){ //detect if the input file has next line
            A = B = C = D = F = 0;
            avg = 0.0;
            number = input.nextInt();
            min = max = number;
            total = count = 0;
            
            while(number != -1){
                if(number < min){
                    min = number;
                }
                if(number > max){
                    max = number;
                }
                count++;
                total += number;
                if(number >= 90){
                    A++;
                }
                else if(number >= 80){
                    B++;
                }
                else if(number >= 70){
                    C++;
                }
                else if(number >= 60){
                    D++;
                }
                else{
                    F++;
                }
                
                number = input.nextInt();
            }
            
            output.println("Set " + set + " of grades calculated");
            set++;
            
            if(count == 0){
                output.println("No grades to average.\n\n");
            }
            else{
                avg = (double)total / count;//typr cast tp double
                output.println("Number of As: " + A);
                output.println("Number of Bs: " + B);
                output.println("Number of Cs: " + C);
                output.println("Number of Ds: " + D);
                output.println("Number of Fs: " + F);
                output.println("The high score was: " + max);
                output.println("The low score was: " + min);
                output.printf("The average score is %.1f\n\n" ,avg);
            }
        }
        
        System.out.println("Grade processing is completed");
        System.out.println("You can retrieve the output file at, "+ inOutFile);
        input.close();
        output.close();
    }
}